name: Build APK

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "20"

            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.24.3"

            - name: Install dependencies
              run: flutter pub get

            - name: Build APK
              run: flutter build apk --release

            - name: Upload built apk to Google Drive
              uses: Jodebu/upload-to-drive@master
              with:
                  target: "build/app/outputs/flutter-apk/app-release.apk"
                  credentials: secrets.ENCODED_CREDENTIALS_SMARTPAY
                  folder: secrets.GOOGLE_DRIVE_ID
