name: Build APK

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "20"

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.29.2"
                  channel: "stable"

            - name: Install dependencies
              run: flutter pub get

            - name: Create .env file
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  API_KEY: ${{ secrets.API_KEY }}
              run: |
                  echo "API_URL=${BASE_URL}" > .env
                  echo "API_KEY=${API_KEY}" >> .env

            - name: Build APK
              run: flutter build apk --release

            - name: Upload APK artifact
              uses: actions/upload-artifact@v3.1.3
              with:
                  name: release-apk
                  path: build/app/outputs/flutter-apk/app-release.apk
