name: Build APK and Upload to Google Drive

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "20"

            - name: Install Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.29.3"

            - name: Install dependencies
              run: flutter pub get

            - name: Create .env file
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  API_KEY: ${{ secrets.API_KEY }}
              run: |
                  echo "API_URL=${BASE_URL}" > .env
                  echo "API_KEY=${API_KEY}" >> .env

            - name: Build APK
              run: flutter build apk --release

            - name: Upload APK artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: build/app/outputs/flutter-apk/app-release.apk

            - name: Upload apk to Google Drive
              uses: logickoder/g-drive-upload@1.0.0
              with:
                  credentials: ${{ secrets.GCP_CREDENTIAL }}
                  filename: "build/app/outputs/flutter-apk/app-release.apk"
                  folderId: ${{ secrets.GOOGLE_FOLDER_ID }}
                  overwrite: "true"
